// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchZ7Im4fLRG42bNLGPPOQltlgbSdbu_c',
    appId: '1:554383408377:web:849e2f683835c30d73f628',
    messagingSenderId: '554383408377',
    projectId: 'netmatch-dc82e',
    authDomain: 'netmatch-dc82e.firebaseapp.com',
    storageBucket: 'netmatch-dc82e.firebasestorage.app',
    measurementId: 'G-69PX6MYWZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwyxUyX2EenA1asF0YXyj6bfBSulybR3g',
    appId: '1:554383408377:android:bee891be8749295173f628',
    messagingSenderId: '554383408377',
    projectId: 'netmatch-dc82e',
    storageBucket: 'netmatch-dc82e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw_izITOFdCDQxY6dYtm_f1tk5LuNSQDY',
    appId: '1:554383408377:ios:03236e0f7241b5fe73f628',
    messagingSenderId: '554383408377',
    projectId: 'netmatch-dc82e',
    storageBucket: 'netmatch-dc82e.firebasestorage.app',
    iosBundleId: 'com.example.netmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw_izITOFdCDQxY6dYtm_f1tk5LuNSQDY',
    appId: '1:554383408377:ios:03236e0f7241b5fe73f628',
    messagingSenderId: '554383408377',
    projectId: 'netmatch-dc82e',
    storageBucket: 'netmatch-dc82e.firebasestorage.app',
    iosBundleId: 'com.example.netmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchZ7Im4fLRG42bNLGPPOQltlgbSdbu_c',
    appId: '1:554383408377:web:b9e3dc9c614ad2b273f628',
    messagingSenderId: '554383408377',
    projectId: 'netmatch-dc82e',
    authDomain: 'netmatch-dc82e.firebaseapp.com',
    storageBucket: 'netmatch-dc82e.firebasestorage.app',
    measurementId: 'G-FSRT809M1H',
  );
}
